ТЗ 15 доработка функционала бронирования и комментариев
elmuss/java-shareit pull request #2
Opened 2024-09-03 12:12 UTC by elmuss

2024-09-05 04:35 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "status")
Для статуса лучше сделать enum и использовать его след. образом
```
@Enumerated(EnumType.STRING)
@Column(name = "status", nullable = false)
private BookingStatus status;
```

2024-09-05 04:38 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Optional<User> booker = userRepository.findById(userId);
Можно короче
```
User booker = userRepository.findById(userId)
	.orElseThrow(() -> new NotFoundException(USER_NOT_FOUND_MSG);
```

2024-09-05 04:40 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case "CURRENT" -> bookingRepository.findByStartBeforeAndEndAfter(givenTime, givenTimeEnd).stream()
Вместо строк лучше сделать и использовать перечислимое

2024-09-05 04:42 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Getter
В dto вместо геттера-сеттера можно использовать одну аннотацию `@Data`

2024-09-05 04:43 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
InMemory реализация больше не понадобится, удаляем из проекта

2024-09-05 04:46 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public CommentDto create(@PathVariable @Min(1) int id,
Чтобы аннотации на параметрах типа `@Min(1)` сработали, на класс контроллера нужно навесить  `@Validated`

2024-09-05 04:58 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Не увидел использования `@Transactional`.
Обычно на класс реализации сервисов навешивают `@Transactional(readOnly = true)`, а на методы, где есть изменения данных '@Transactional'. Понятно, что в данной работе будет и без этого все работать, но нужно стараться использовать описанный мной подход.

Вот коммент от авторов спринга
"Reading methods like findAll() and findOne(…) are using @Transactional(readOnly = true) which is not strictly necessary but triggers a few optimizations in the transaction infrastructure (setting the FlushMode to MANUAL to let persistence providers potentially skip dirty checks when closing the EntityManager). Beyond that the flag is set on the JDBC Connection as well which causes further optimizations on that level. "

2024-09-05 05:00 UTC, VadimZharkov requested changes
Можно улучшить

2024-09-05 14:22 UTC, elmuss commented
Поправила по замечаниям

2024-09-06 04:04 UTC, VadimZharkov approved these changes

2024-09-11 12:21 UTC, merged